### ISSUE TITLE
Add former WRUG members

### ISSUE THREAD

**Issue by ccamara** [WarwickRUG/WarwickRUG.github.io#21]
There's people who were very active WRUG members who, for diverse reasons, are no longer members. It would be nice crediting them besides the all-contributors section on the Readme file.

**Comment by ccamara** [comment]
I've added @Selbosh  and @ashenvi10 to https://warwickrug.github.io/about.html 

@Selbosh , do you know of anyone else we should be adding there?

**Comment by Selbosh** [comment]
Lewis Rendell

**Comment by ccamara** [comment]
Thank you!
