### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by EllaKaye** [WarwickRUG/WarwickRUG.github.io#27]
Great job with the website so far @ccamara!

On some of the people pages, there's no icon showing in the button for their website. In the source code, they're listed as `icon: web` but web isn't a valid bootstrap 5 icon name. I suggest using `icon: globe` instead. For some reason, this has been done for my page (not by me!) but not any of the others. A project-wide 'find and replace' should sort the issue fully and quickly. I'm a bit tight on time at the moment, hence raising it as an issue rather than submitting a PR - hope you don't mind.

Also, there is no 'meetup' icon, so I suggest using `calendar` for the icon on line 14 of `index.qmd` (as you do for the navbar).

**Comment by ccamara** [comment]
Well spotted! Fixed now
