### ISSUE TITLE
WRUG twitter

### ISSUE THREAD

**Issue by EllaKaye** [WarwickRUG/WarwickRUG.github.io#28]
The twitter icon in the navbar goes to the twitter home page, rather than the WRUG page, so line 26 of `_quarto.yml` needs updating to <https://twitter.com/WarwickRUG>.

I don't think that WarwickRUG (or indeed anyone who cares about democracy and decency) should be active on twitter anymore, but that's a whole other discussion.

**Comment by ccamara** [comment]
I would be happy to remove Twitter's link, to be honest

**Comment by hturner** [comment]
Most of the people that have engaged with the Twitter account in the past are people we have contact with in other ways, so I agree, we can remove the Twitter link.

I've also removed it from the TODO list on our organizing meetup issue template.

**Comment by ccamara** [comment]
Great, thanks! Just removed it

@hturner , that makes me think that maybe we could include a note on Twitter's bio or a fixed tweet pointing to our mastodon account and stating that we are not monitoring it as frequently (or not at all)?

**Comment by EllaKaye** [comment]
Thanks @ccamara and @hturner. Agreed, such a note and pinned tweet on Twitter would be a good idea.

**Comment by hturner** [comment]
Good idea about the bio and pinned tweet - I've done that now.
